services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KC_LOG_LEVEL: INFO
      ROOT_LOGLEVEL: INFO
    ports:
      - '8080:8080'
    command: start-dev --verbose
    depends_on:
      - keycloak-postgres
    networks:
      - keycloak-net
      - spa-net

  keycloak-postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak-net
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  backend-db:
    image: postgres
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: api
      POSTGRES_PASSWORD: password
    command: -p 5433
    ports:
      - '5433:5433'
    networks:
      - backend-net
    volumes:
      - backend-db-data:/var/lib/postgresql/data

  backend:
    build: ./AuthService/AuthService
    ports:
      - '4001:8080'
    depends_on:
      - backend-db
      - keycloak
    networks:
      - backend-net
      - keycloak-net

  flask-api:
    build:
      context: ./model
    ports:
      - '5000:5000'
    volumes:
      - ./model:/app
    environment:
      FLASK_ENV: development

  nextjs-app:
    build:
      context: ./stock-predictor-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_URL_INTERNAL: http://nextjs-app:3000
      AUTH_SERVER_URL: http://keycloak:8080
      JWK_SET_URI: http://keycloak:8080/realms/myrealm/protocol/openid-connect/certs
      NEXT_LOCAL_KEYCLOAK_URL: http://localhost:8080
      NEXT_CONTAINER_KEYCLOAK_ENDPOINT: http://keycloak:8080
      END_SESSION_URL: http://keycloak:8080/realms/myrealm/protocol/openid-connect/logout
    networks:
      - backend-net
      - keycloak-net
      - spa-net
    depends_on:
      - flask-api
      - backend
      - keycloak

volumes:
  backend-db-data:
  keycloak-db-data:

networks:
  keycloak-net:
  backend-net:
  spa-net:
