apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__Postgres
              value: Host=backend-db.default;Port=5433;Database=api;Username=api;Password=password
            - name: Keycloak__auth-server-url
              value: http://keycloak.default:8080/
            - name: Keycloak__confidential-port
              value: '0'
            - name: Keycloak__credentials__secret
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: Keycloak__credentials__secret
            - name: Keycloak__realm
              value: myrealm
            - name: Keycloak__resource
              value: api-client
            - name: Keycloak__ssl-required
              value: none
          image: stockpredictor-backend
          imagePullPolicy: Never
          name: backend
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: '256Mi'
              cpu: '375m'
            limits:
              memory: '512Mi'
              cpu: '750m'
      restartPolicy: Always
