apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: flask-imitation
  name: flask-imitation
spec:
  type: NodePort
  ports:
    - name: '5000'
      port: 5000
      targetPort: 5000
      nodePort: 30003
  selector:
    io.kompose.service: flask-imitation
