apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  type: NodePort
  ports:
    - name: '8080'
      port: 8080
      targetPort: 8080
      nodePort: 30002
  selector:
    io.kompose.service: keycloak
