apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nextjs-app
  name: nextjs-app
spec:
  type: NodePort
  ports:
    - name: '3000'
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    io.kompose.service: nextjs-app
