apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nextjs-app
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextjs-app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nextjs-app
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: development
          image: stockpredictor-nextjs-app
          imagePullPolicy: Never
          name: nextjs-app
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '512Mi'
              cpu: '1'
      restartPolicy: Always
